# Generated by Django 4.2.16 on 2024-12-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_remove_category_quotes_quote_category_alter_quote_id'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_affirmations',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='past_affirmations',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_affirmations',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='favorited_profiles', to='quotes.quote'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='past_affirmations',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='past_profiles', to='quotes.quote'),
        ),
    ]
