# Generated by Django 4.2.16 on 2024-12-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_remove_category_quotes_quote_category_alter_quote_id'),
        ('user_profile', '0002_remove_userprofile_favorite_affirmations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_affirmations',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorited_profiles', to='quotes.quote'),
        ),
    ]
