# Generated by Django 4.2.16 on 2024-12-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('favorite_scent', models.CharField(blank=True, default='', max_length=255)),
                ('product_link', models.URLField(blank=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_info', models.TextField(blank=True, null=True)),
                ('author_name', models.CharField(max_length=255)),
                ('number_of_shares', models.IntegerField(default=0)),
                ('quote_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('is_premium', models.BooleanField(default=False)),
                ('wants_to_feel', models.CharField(blank=True, default='', max_length=255)),
                ('product', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category', to='quotes.product')),
                ('quotes', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category', to='quotes.quote')),
            ],
        ),
    ]
