# Generated by Django 4.2.16 on 2024-11-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('is_premium', models.BooleanField(default=False)),
                ('wants_to_feel', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='categories',
            name='product',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='quotes',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Quotes',
            new_name='Quote',
        ),
    ]
