# Generated by Django 4.2.16 on 2024-11-18 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_category'),
        ('quotes', '0002_category_remove_categories_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category', to='quotes.product'),
        ),
        migrations.AddField(
            model_name='category',
            name='quotes',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category', to='quotes.quote'),
        ),
    ]
