# Generated by Django 4.2.16 on 2024-12-15 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_category_product_alter_category_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category', to='quotes.product'),
        ),
        migrations.AlterField(
            model_name='category',
            name='quotes',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category', to='quotes.quote'),
        ),
    ]
